{% set name = "pyroll" %}
{% set version = "2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyroll-{{ version }}.tar.gz
  sha256: ced7e456ee8bfc845043b96c2ff63bf28371d0818b7f3e4be5ed15dca29b3f5b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - pyroll-core >=2.0.0,<3.0.0
    - pyroll-cli >=2.0.0,<3.0.0
    - pyroll-report >=2.0.0,<3.0.0
    - pyroll-export >=2.0.0,<3.0.0

test:
  imports:
    - pyroll
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pyroll.readthedocs.io
  summary: A meta package for installing quickly the PyRolL Core, CLI, Report and Export. The provided functionality is similar to the old pyroll package, which was split up into distinct packages with version 2.0.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
